version: '3'

services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app:cached
    ports:
      - "3000:3000"
    environment:
      WEATHER_API_ENDPOINT: https://api.openweathermap.org/data/2.5/onecall
      WEATHER_API_KEY: "fake_key"
